{% set name = "pyjams" %}
{% set version = "2.0" %}
{% set sha256 = "a00df854b9026b00abc7abd3fa523fbf5a52292532b6a61e3866d74ce405db3c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyjams-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=42
    - setuptools_scm >=3.5
  run:
    - python >=3.8
    - numpy
    - scipy
    - matplotlib-base
    - pandas
    - schwimmbad
    - cftime
    - netcdf4
    - xlrd
    - openpyxl

test:
  imports:
    - pyjams
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mcuntz/pyjams
  summary: 'General Python package with a wide variety of miscellaneous utility functions.'
  dev_url: https://github.com/mcuntz/pyjams
  license: MIT
  license_file: LICENSE
  description: |
    pyjams is a general Python package offering a wide variety of miscellaneous
    functions in different categories, such as reading different file formats,
    date conversion routines, or calculating Elementary Effects. It has several
    subpackages offering constants, special functions, or objective functions
    to be used with scipy.optimize or similar.
  doc_url: https://mcuntz.github.io/pyjams
  dev_url: https://github.com/mcuntz/pyjams

extra:
  recipe-maintainers:
    - mcuntz
