{% set name = "pyjams" %}
{% set version = "1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyjams-{{ version }}.tar.gz
  sha256: 9e5f2a281e0f883994d45ed9b4fdf106361d887473d31c68ece07da6c5360ca2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=42
    - setuptools_scm >=3.5
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib-base
    - schwimmbad

test:
  imports:
    - pyjams
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mcuntz/pyjams
  summary: 'General Python package with miscellaneous utility functions used in several other packages.'
  dev_url: https://github.com/mcuntz/pyjams
  license: MIT
  license_file: LICENSE
  description: |
    pyjams is a general Python package offering miscellaneous functions in
    different categories, such as reading different file formats, Julian date
    routines, or calculating Elementary Effects. It has several subpackages
    offering constants or special functions, or objective functions to be
    used with scipy.optimize or similar.
  doc_url: https://pyjams.readthedocs.io/
  dev_url: https://github.com/mcuntz/pyjams

extra:
  recipe-maintainers:
    - mcuntz
