{% set name = "pyjams" %}
{% set version = "1.32" %}
{% set sha256 = "f66b2f8514cea9c2569678bd5ae6cefdaab66b457b6010be449227725706c7af" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyjams-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=42
    - setuptools_scm >=3.5
  run:
    - python >=3.8
    - numpy
    - scipy
    - matplotlib-base
    - schwimmbad
    - cftime
    - netcdf4
    - xlrd
    - openpyxl

test:
  imports:
    - pyjams
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mcuntz/pyjams
  summary: 'General Python package with miscellaneous utility functions used in several other packages.'
  dev_url: https://github.com/mcuntz/pyjams
  license: MIT
  license_file: LICENSE
  description: |
    pyjams is a general Python package offering miscellaneous functions in
    different categories, such as reading different file formats, Julian date
    routines, or calculating Elementary Effects. It has several subpackages
    offering constants or special functions, or objective functions to be
    used with scipy.optimize or similar.
  doc_url: https://mcuntz.github.io/pyjams
  dev_url: https://github.com/mcuntz/pyjams

extra:
  recipe-maintainers:
    - mcuntz
